#!/bin/bash
if [[ $OSTYPE == darwin* ]]; then
    alias flush='dscacheutil -flushcache'

    # Global Bash #
    alias c='clear'
    alias lsa='ls -al'
    alias lla='ll -al'
    alias cd~='cd $HOME'
    alias cd.='cd ..'
    alias cd..='cd ../../'
    alias cd...='cd ../../../'
    alias vizsh='vim ~/.zshrc'
    alias vialias='vim ~/.aliases'
    alias sozsh='source ~/.zshrc'
    alias vihosts='sudo vim /etc/hosts'
    alias upzsh='upgrade_oh_my_zsh'
    alias hs='history | grep'
    alias mkcd='function _mkcd(){ mkdir -p "$1"; cd "$1" };_mkcd'
    alias rm:f='rm -rf'

    # Application
    alias slack='open -a /Applications/Slack.app'
    alias tower='open -a /Applications/Tower.app'
    alias paw='open -a /Applications/Paw.app'
    alias tplus='open -a /Applications/TablePlus.app'

    # Path
    alias pphp='cd $HOME/projects/php'
    alias pjs='cd $HOME/projects/js'
    alias dl='cd $HOME/Downloads'

    # Tree
    alias tree='tree -C'

    # Git Command Alises #
    alias g='git'
    alias g:i='git init'
    alias g:s='git status'
    alias g:a.='git add .'
    alias g:aa='git add -All'
    alias g:b='function _gbranch(){ git branch -$1 };_gbranch'
    alias g:bd='git branch -D'
    alias g:bdf='function _gbranchdf(){ git push $1 --delete --force };_gbranchdf'
    alias g:cl='git clone'
    alias g:cm='function _gcommit(){ git commit -m $1 };_gcommit'
    alias g:co='git checkout'
    alias g:mr='git merge'
    alias g:mrs='git merge --no-ff --no-commit'
    alias g:ps='git push -u'
    alias g:ra='git remote add'
    alias g:rr='git remote rm'
    alias g:rv='git remote -v'
    alias g:pl='git pull'
    alias g:pull='function _gpull(){ git pull ${1:-origin} "$(git symbolic-ref --short HEAD)" };_gpull'
    alias g:push='function _gpush(){ git push ${1:-origin} "$(git symbolic-ref --short HEAD)" };_gpush'
    alias g:t='git tag'
    alias g:tag='git_tagging'

    # Git Flow
    alias gf='git flow'
    alias gf:i='git flow init'
    alias g:cod='git checkout develop'
    alias g:coh='git checkout hotfix'
    alias g:cor='git checkout release'
    alias gf:f='git flow feature'
    alias gf:h='git flow hotfix'
    alias gf:r='git flow release'
    alias gf:fs='git flow feature start'
    alias gf:hs='git flow hotfix start'
    alias gf:rs='git flow release start'
    alias gf:ff='git flow feature finish'
    alias gf:fp='git flow feature publish'
    alias gf:hf='git flow hotfix finish'
    alias gf:rf='git flow release finish'
    alias gf:fp='git flow feature publish'
    alias gf:hp='git flow hotfix publish'
    alias gf:rp='git flow release publish'
    alias gf:fp='git flow feature pull'

    # Homebrew Services
    alias s:ls='brew services list'
    alias s:php='function _sphp(){ brew services $1 php };_sphp'
    alias s:ngx='function _sngx(){ brew services $1 nginx };_sngx'
    alias s:rdb='function _sredis(){ brew services $1 redis };_sredis'
    alias s:mdb='function _smydb(){ brew services $1 mysql };_smydb'
    alias s:pdb='function _spodb(){ brew services $1 postgresql };_spodb'
    alias s:web='function _sweb(){ s:php $1 && s:mydb $1 && s:ngx $1 };_sweb'

    # NodeJs NPM #
    alias node:v='node -v'
    alias npm:v='npm -v'
    alias npm:i='npm init'
    alias npm:in='npm install'
    alias npm:ud='npm update'
    alias npm:dev='npm run dev'
    alias npm:build='npm run build'
    alias npm:build:s='npm run build-staging'
    alias npm:build:p='npm run build-production'
    alias npm:audit='npm audit fix'
    alias npm:audit:f='npm audit fix --force'

    # PHP Composer
    # alias com='composer'
    alias com:v='composer -V'
    alias com:i='composer init'
    alias com:in='composer install'
    alias com:ud='composer update'
    alias com:ud:g='composer global update'
    alias com:ug='composer upgrade'
    alias com:re='composer require'
    alias com:re:g='composer global require'
    alias com:re:d='composer require --dev'
    alias com:rm='composer remove'
    alias com:rm:d='composer remove --dev'
    alias com:gs='composer global show'

    # Laravel Artisan
    alias pa='php artisan'
    alias pa:ls='pa list'
    alias pa:v='pa --version'

    alias web:new='new_website_project'
fi
