#!/bin/bash

DISABLE_WELCOME_MESSAGE=false
ASAP_APP_NAME='BLACK BOX'

# Color Palette
RESET='\033[0m'
BOLD='\033[1m'

## Foreground
BLACK='\033[38;5;0m'
RED='\033[38;5;1m'
GREEN='\033[38;5;2m'
YELLOW='\033[38;5;3m'
BLUE='\033[38;5;4m'
MAGENTA='\033[38;5;5m'
CYAN='\033[38;5;6m'
WHITE='\033[38;5;7m'

## Background
ON_BLACK='\033[48;5;0m'
ON_RED='\033[48;5;1m'
ON_GREEN='\033[48;5;2m'
ON_YELLOW='\033[48;5;3m'
ON_BLUE='\033[48;5;4m'
ON_MAGENTA='\033[48;5;5m'
ON_CYAN='\033[48;5;6m'
ON_WHITE='\033[48;5;7m'

MODULE="$(basename $0)"

log() {
  echo -e "${NAMI_DEBUG:+${CYAN}${MODULE} ${MAGENTA}$(date "+%T.%2N ")}${RESET}${@}" >&2
}

info() {
  log "${GREEN}INFO ${RESET} ==> ${@}"
}

warn() {
  log "${YELLOW}WARN ${RESET} ==> ${@}"
}

error() {
  log "${RED}ERROR${RESET} ==> ${@}"
}

print_welcome_page() {
  if [ -z "$DISABLE_WELCOME_MESSAGE" ]; then
    if [ -n "$ASAP_APP_NAME" ]; then
      print_image_welcome_page
    fi
  fi
}

# Prints the welcome page for this Bitnami Docker image
print_image_welcome_page() {
  # log ""
  log "${BOLD}${RED}|>|>|>${RESET} ${GREEN}Welcome to the ${BOLD}${GREEN}${ASAP_APP_NAME}${RESET} ${GREEN}command${RESET} ${BOLD}${RED}<|<|<|${RESET}"
  # log "${BOLD}${RED}|>${RESET} ${GREEN}Terminal command on the MacOS Catalina${RESET}"
  # log ""
}

function new_website_project() {
  if [[ ( $1 == "--help") ||  $1 == "-h" ]]
	then
    info "Create project use Laravel or Lumen."
    info "Syntax: web:new -[h]"
    info "Follow the convention and select option which framework do you use."
    info "options: 1. Laravel or 2. Lumen"
    info "Print this Help."
  else
    new_site
  fi
}

function create_nginx_virtual_host() {
  project_location=$HOME'/projects/www'

  cat > ~/.config/vhosts/$2 <<EOF
server {
    listen 80;
    listen [::]:80;

    server_name $2.asap;
    set $base $project_location/$1;
    root $base/public;

    index index.html index.htm index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    error_page 404 /index.php;

    location ~ \.php$ {
        include snippets/php_fastcgi.conf;
    }

    # additional config
    include snippets/general.conf;

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
EOF
}

function laravel_project() {
    pwd_location=$PWD
    project_location=$HOME/'projects/www'
    cd $project_location && laravel new $1 && cd $pwd_location
}

function lumen_project() {
    pwd_location=$PWD
    project_location=$HOME/'projects/www'
    cd $project_location && lumen new $1 && cd $pwd_location
}

function new_site() {
  PS3="Which PHP framework do you want use? "
  select opt in Laravel Lumen
  do
    case $opt in
      Laravel)
        php_framework "laravel";
        break;;
      Lumen)
        php_framework "lumen";
        break;;
      quit)
        break;;
      *)
        error "Invalid option $REPLY";;
    esac
  done
}

function php_framework() {
  echo -n "Enter project directory name: "
  read project_dir
  echo -n "Enter project virtual host for Nginx: "
  read project_host

  if [ ! -z "$project_dir" ] && [ ! -z "$project_host" ]
  then
    info "** Create new $1 project ${project_dir}"
    $1_project $project_dir
    info "** Create virtual host ${BOLD}${project_host}.asap${RESET}"
    create_nginx_virtual_host $project_dir $project_host
    info "** Append dns ${BOLD}${project_host}.asap${RESET} to hosts for local user"
    echo "127.0.0.1   ${project_host}.asap" | sudo tee -a /etc/hosts >/dev/null
    # info "** Reload Nginx service"
    # nginx -s reload
    info "Done... and you can try to access on browser with url: ${BOLD}${project_host}.asap${RESET}"
  else
    warn "** Please check your input project diectory and vhost."
  fi
}
